// <auto-generated />
using System;
using COMP702_WindTurbine.database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace COMP702_WindTurbine.Migrations
{
    [DbContext(typeof(MonitoringDbContext))]
    [Migration("20260328041253_AddPitchAngleAndGearboxOilTemp")]
    partial class AddPitchAngleAndGearboxOilTemp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("COMP702_WindTurbine.models.Alert", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ClearedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TurbineId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("TurbineId");

                    b.ToTable("Alert");
                });

            modelBuilder.Entity("COMP702_WindTurbine.models.Turbine", b =>
                {
                    b.Property<string>("TurbineId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastTelemetryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TurbineId");

                    b.ToTable("Turbine");
                });

            modelBuilder.Entity("COMP702_WindTurbine.models.TurbineTelemetry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double?>("Efficiency")
                        .HasColumnType("double precision");

                    b.Property<double?>("GearboxOilTemp")
                        .HasColumnType("double precision");

                    b.Property<double?>("PitchAngle")
                        .HasColumnType("double precision");

                    b.Property<double?>("PowerOutput")
                        .HasColumnType("double precision");

                    b.Property<double?>("RotorSpeed")
                        .HasColumnType("double precision");

                    b.Property<bool?>("StartedAlert")
                        .HasColumnType("boolean");

                    b.Property<double?>("Temperature")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TurbineId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("Vibration")
                        .HasColumnType("double precision");

                    b.Property<double?>("WindSpeed")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("TurbineId");

                    b.ToTable("TurbineData");
                });

            modelBuilder.Entity("COMP702_WindTurbine.models.Alert", b =>
                {
                    b.HasOne("COMP702_WindTurbine.models.Turbine", "Turbine")
                        .WithMany("Alerts")
                        .HasForeignKey("TurbineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Turbine");
                });

            modelBuilder.Entity("COMP702_WindTurbine.models.TurbineTelemetry", b =>
                {
                    b.HasOne("COMP702_WindTurbine.models.Turbine", "Turbine")
                        .WithMany("TelemetryHistories")
                        .HasForeignKey("TurbineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Turbine");
                });

            modelBuilder.Entity("COMP702_WindTurbine.models.Turbine", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("TelemetryHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
